version: '3.8'
services:
  xmtp-webhook-itest:
    image: node:18
    depends_on:
      - localstack-itest
    user: "node"
    working_dir: /home/node/app
    environment:
      AWS_ACCESS_KEY_ID: anythingwilldoforlocalstack
      AWS_ENDPOINT: http://localstack:4566
      AWS_REGION: us-east-1
      AWS_SECRET_ACCESS_KEY: anythingwilldoforlocalstack
      AWS_SQS_QUEUE_GAME_URL: http://sqs.us-east-1.localhost.localstack.cloud:4566/000000000000/game_notifications.fifo
      AWS_SQS_QUEUE_USERS_URL: http://sqs.us-east-1.localhost.localstack.cloud:4566/000000000000/user_notifications.fifo
      FREESTUFF_API_KEY: ${FREESTUFF_API_KEY}
      FREESTUFF_WEBHOOK_PORT: 12345
      FREESTUFF_WEBHOOK_SECRET: wdaji29dJadj91jAjd9a92eDak2
      KEY: ${XMTP_BOT_KEY}
      XMTP_ENV: dev
    volumes:
      - ./:/home/node/app
    ports:
      - "12345:12345"
    command: "node webhook.js"
  xmtp-bot-itest:
    image: node:18
    depends_on:
      - localstack-itest
    user: "node"
    working_dir: /home/node/app
    environment:
      AWS_ACCESS_KEY_ID: anythingwilldoforlocalstack
      AWS_ENDPOINT: http://localstack:4566
      AWS_REGION: us-east-1
      AWS_SECRET_ACCESS_KEY: anythingwilldoforlocalstack
      KEY: ${XMTP_BOT_KEY}
      XMTP_ENV: dev
    volumes:
      - ./:/home/node/app
    command: "node bot.js"
  localstack-itest:
    container_name: "localstack"
    image: localstack/localstack:3.0.2
    environment:
      DYNAMODB_SHARE_DB: 1
      SERVICES: dynamodb,sqs
    ports:
      - "4566:4566"
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - ".docker/localstack/bootstrap:/etc/localstack/init/ready.d"